name: Bug report
description: Report a reproducible problem
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: input
    attributes:
      label: Version
